package cn.finwood.demo.model.po;

import java.util.Date;

public class BaseDo {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.created_by
    *
    * @mbg.generated
    */
   private Long createdBy;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.created_by_name
    *
    * @mbg.generated
    */
   private String createdByName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.creator_type
    *
    * @mbg.generated
    */
   private Integer creatorType;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.created_time
    *
    * @mbg.generated
    */
   private Date createdTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.created_ip
    *
    * @mbg.generated
    */
   private String createdIp;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.last_modified_by
    *
    * @mbg.generated
    */
   private Long lastModifiedBy;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.last_modified_by_name
    *
    * @mbg.generated
    */
   private String lastModifiedByName;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.last_modifier_type
    *
    * @mbg.generated
    */
   private Integer lastModifierType;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.last_modified_time
    *
    * @mbg.generated
    */
   private Date lastModifiedTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.last_modified_ip
    *
    * @mbg.generated
    */
   private String lastModifiedIp;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_brand.valid
    *
    * @mbg.generated
    */
   private Integer valid;

    public Long getCreatedBy() {
        return createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
    
    public String getCreatedByName() {
        return createdByName;
    }
    
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }
    
    public Integer getCreatorType() {
        return creatorType;
    }
    
    public void setCreatorType(Integer creatorType) {
        this.creatorType = creatorType;
    }
    
    public Date getCreatedTime() {
        return createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    
    public String getCreatedIp() {
        return createdIp;
    }
    
    public void setCreatedIp(String createdIp) {
        this.createdIp = createdIp;
    }
    
    public Long getLastModifiedBy() {
        return lastModifiedBy;
    }
    
    public void setLastModifiedBy(Long lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }
    
    public String getLastModifiedByName() {
        return lastModifiedByName;
    }
    
    public void setLastModifiedByName(String lastModifiedByName) {
        this.lastModifiedByName = lastModifiedByName;
    }
    
    public Integer getLastModifierType() {
        return lastModifierType;
    }
    
    public void setLastModifierType(Integer lastModifierType) {
        this.lastModifierType = lastModifierType;
    }
    
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }
    
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }
    
    public String getLastModifiedIp() {
        return lastModifiedIp;
    }
    
    public void setLastModifiedIp(String lastModifiedIp) {
        this.lastModifiedIp = lastModifiedIp;
    }
    
    public Integer getValid() {
        return valid;
    }
    
    public void setValid(Integer valid) {
        this.valid = valid;
    }
       
}
